version: "3"

services:
  client:
    build:
      context: ./
      dockerfile: dev.dockerfile
    ports:
      - 3000:3000
    command: yarn dev
    volumes:
      - ./src/app/src
      - ./public:/app/public
